spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${{ secrets.MYSQL_URL }}/ecommerce?serverTimezone=Asia/Seoul
    username: ${{ secrets.MYSQL_USERNAME }}
    password: ${{ secrets.MYSQL_PASSWORD }}
    data: classpath:/data.sql
#    initialization-mode: always
security:
  google:
    client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
    client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
cloud:
  aws:
    credentials:
      access-key: ${{ secrets.AWS_ACCESS_KEY }}
      secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    s3:
      bucket: ${{ secrets.IMAGE_BUCKET }}
    region:
      static: ap-northeast-2
    stack:
      auto: false