name: [PR]Java CI with Gradle

on:
  pull_request:
    branches: [ "dev" ]
      
permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: s3-jar
  working-directory: ./server/eCommerce
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
      
    - name: Change mode gradle
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
    - name: Build with Gradle
      run : ./gradlew clean build
      working-directory: ${{ env.working-directory }}
      
    # build한 후 프로젝트를 압축합니다.
    - name: Make zip file
      run: zip -r ./deploy.zip .
      shell: bash
      working-directory: ${{ env.working-directory }}
      
    # Access Key와 Secret Access Key를 통해 권한을 확인합니다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    
    # 압축한 프로젝트를 S3로 전송합니다.
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deploy.zip s3://$S3_BUCKET_NAME/deploy.zip
      working-directory: ${{ env.working-directory }}
      
   # CodeDeploy에게 배로 명령을 내립니다.
    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name eCommerce
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name eCommerce-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy.zip
